---
- import_tasks: setup-redhat.yml
  when: ansible_os_family == "RedHat"

- name: "(Install: Debian/Ubuntu/CentOS/RedHat/FreeBSD) Install NGINX..."
  package:
    name: nginx
    state: present
  when: nginx_install_from == "os_repository"
